package org.sky.threshholdrulz;
import com.hand.guvnor.Message;

no-loop
rule "approval decision by manager"
    when
     m : Message( status == 0 )
    then
    modify( m ){
         m.setMessage( "hello" );
     };
     end


rule "approval decision by general manager"
    when
    m:Message( status == 1 )
    then
    modify(m){
    m.setMessage( "goodbye" );
    }
    end