package hello;


import com.hand.guvnor.Message;

rule "Hello World"
    when
     m : Message( status == 0, myMessage : message )
    then
     System.out.println( myMessage );
     m.setMessage( "Goodbye cruel world" );
     m.setStatus( Message.GOODBYE );
     update( m );
     end


rule "GoodBye"
    when
     Message( status == 1, myMessage : message )
    then
    System.out.println( myMessage );

    end