package com.hand.guvnor;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Message implements java.io.Serializable
{

    public static final int HELLO = 0;
    
    public static final int GOODBYE = 1;

   static final long serialVersionUID = 1L;

   private java.lang.String massage;

   private java.lang.Integer status;

   public Message()
   {
   }

   public java.lang.String getMassage()
   {
      return this.massage;
   }

   public void setMassage(java.lang.String massage)
   {
      this.massage = massage;
   }

   public java.lang.Integer getStatus()
   {
      return this.status;
   }

   public void setStatus(java.lang.Integer status)
   {
      this.status = status;
   }

   public Message(java.lang.String massage, java.lang.Integer status)
   {
      this.massage = massage;
      this.status = status;
   }

}